### ISSUE TITLE
Comparison with SpatialLinesNetwork

### ISSUE THREAD

**Issue by Robinlovelace** [garciapintado/SpatialGraph#1]
This isn't an issue so much as a question: how does your package relate to the `SpatialLinesNetwork` class in [**stplanr**](https://github.com/ropensci/stplanr)?

I'm asking because am thinking about splitting-out that class definition into a separate package akin to the dormant https://github.com/edzer/spnetwork project with @edzer - possibly the subject of a 'minihack' in Munster around the 7th January.

FYI the following code chunks provide a basic summary of `SpatialLinesNetwork`. Curious to learn how it compares with the class definition in this package - could at some point switch to using this or another class system for our purposes in **stplanr**, although that may take some time/work. More broadly: great to see other ways of thinking about this.

``` r
library(stplanr)
rnet = SpatialLinesNetwork(route_network_sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
rnet@sl$centrality = igraph::edge_betweenness(graph = rnet@g)
lwd = rnet@sl$centrality / mean(rnet@sl$centrality)
plot(rnet, lwd = lwd)
```

![](https://i.imgur.com/ieqdeBe.png)

<sup>Created on 2018-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by garciapintado** [comment]
Hallo Robin,
The functions is this package are actually around 4-5 years old, as I developed them for a paper, in which I could not find what I needed in the R repository. I've published it now as other more recent package I've prepared depend on these functions. I was not (and have not been) aware of package stplanr until your message. I'll look at this over this days and reply...

**Comment by garciapintado** [comment]
Hallo Robin,
I can see the definition of "SpatialLinesNetwork" in stplanr:

setClass("SpatialLinesNetwork", representation(
  sl = "SpatialLinesDataFrame",
  g = "igraph", nb = "list", weightfield = "character"
),
validity = function(object) {
  stopifnot(length(object@sl) == length(igraph::E(object@g)))
  stopifnot(length(object@nb) == length(igraph::V(object@g)))
}
)

which can be compared with the "SpatialGraph" class:

setClass("SpatialGraph",
         representation(v='SpatialPointsDataFrame',
                        e='SpatialLinesDataFrame',
                        dist='matrix',
                        path='matrix'),
         validity = function(object) {
           if (!all(object@e@data[,'v0'] %in% object@v@data[,'ID']))
             stop("v0 vertices in edges not found")
           if (!all(object@e@data[,'v1'] %in% object@v@data[,'ID']))
             stop("v1 vertices in edges not found")
           return(TRUE)
         }
)

As you can see, the "SpatialGraph" does not explicitly include an
"igraph". I guess they aim at similar things. One purpose in
"SpatialGraph" is was to save time for online computation of distances
by precalculating the 'dist' and 'path' slots. This was designed with
the purpose of evaluating along-network distances for gridded points
in river networks for flood forecast purposes,
by defining a simple metric. The "SpatialGraph" would provide a precomputed
"skeleton", which the "flesh" (gridded points) uses online to
compute distances for assimilation of satellite Synthetic Aperture
Radar water levels, by mapping the grid into the network. The simple metric used for this, included in the package, is defined in
https://www.sciencedirect.com/science/article/pii/S0022169415001031. It
is great to know about your package. Although I am now working on past
climate analysis, I'll gather the time to look at it in more
detail. Please let me know any thoughts.

**Comment by Robinlovelace** [comment]
Many thanks @garciapintado that answers my question perfectly. Closing for now - we can stay in touch re. any developments either side, e.g. in relation to a new sf implementation.
